services:
  jellyfin:
    image: jellyfin/jellyfin:2025031705-amd64
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - JELLYFIN_PublishedServerUrl=http://unraid.saturn.private/ #optional
    volumes:
      - config:/config
      - tvseries:/data/tvshows
      - movies:/data/movies
      - music:/data/music
    ports:
      - 8096:8096
#      - 8920:8920 #optional
#      - 7359:7359/udp #optional
#      - 1900:1900/udp #optional
    restart: unless-stopped
volumes:
  config:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/user/appdata/jellyfin/config"
      o: bind
  music:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/user/Music"
      o: bind
  tvseries:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/user/TVSeries"
      o: bind
  movies:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/user/Movies"
      o: bind
