---

- hosts: 
    - tower-proxmox
  become: true
  
  tasks: 
    - name: Install rsnapshot if doesnt exist
      apt:
        name: rsnapshot
        force: yes
        update_cache: yes # apt update before installing
    - name: Install sshfs if doesnt exist
      api:
        name: sshfs
        force: yes
    - name: Copy rsnapshot config
      copy: 
        src: ../../rsnapshot/rsnapshot.conf
        dest: /etc/rsnapshot.conf
        owner: root
        group: root
        mode: u=rw,g=r,o=r
    - name: Copy rsnapshot include/exclude settings
      copy:
        src: ../../rsnapshot/filters/
        dest: /etc/rsnapshot
        owner: root
        group: root
        mode: u=rw,g=r,o=r
    # sshfs me@x.x.x.x:/remote/path /local/path/ -o IdentityFile=/path/to/key
    # sshfs -odebug,sshfs_debug,loglevel=debug apollo@192.168.0.232:/share/Proxmox /tmp/sshfs
    - name: Run sshfs and mount to apollo backup folder
      command: echo Mounting!
    - name: Turn off pve service
      command: systemctl stop pve-cluster
    - name: Run backup
      command: rsnapshot alpha
    # for mac: diskutil umount force /tmp/sshfs
    - name: Unmount
      command: echo unmounting!
