services:
  portainer:
    image: portainer/portainer-ce:2.27.0-rc3-linux-amd64
    restart: always
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/user/appdata/portainer"
      o: bind
