---

- hosts: 
    - tower-proxmox
  become: true
  
  tasks: 
    - name: Gather Subset of Facts
      setup: 
        gather_subset: 
          - mounts
    - name: Print mounts
      debug:
        var: ansible_mounts
    - name: Gather disks info
      command: lsblk
      register: result
    - debug:
        var: result.stdout_lines 
    - name: Install rsnapshot if doesnt exist
      apt:
        name: rsnapshot
        force: yes
    - name: Copy rsnapshot config
      copy: 
        src: ../rsnapshot/rsnapshot.conf
        dest: /etc/rsnapshot.conf
        owner: root
        group: root
        mode: u=rw,g=r,o=r
    - name: Copy rsnapshot include/exclude settings
      copy:
        src: ../rsnapshot/filters/
        dest: /etc/rsnapshot
        owner: root
        group: root
        mode: u=rw,g=r,o=r
    - name: Run backup
      command: rsnapshot alpha
