---

- hosts: 
    - tower-proxmox
  become: true
  
  tasks: 
    - name: Gather Subset of Facts
      setup: 
        gather_subset: 
          - mounts
    - name: Print mounts
      debug:
        var: ansible_mounts
    - name: Print disks
      command: lsblk
    # Mount remote hard drive
    # https://serverfault.com/questions/4906/using-dd-for-disk-cloning
    # rsync is safer



